# 开发环境配置
server:
  port: 8080
spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
